language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install libimage-exiftool-perl
  - exiftool -ver
  - gem install echoe
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
notifications:
  email:
    - janfri26@gmail.com